//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMATRANS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon
    {
        public int Num_Bon { get; set; }
        public System.DateTime date_Bon { get; set; }
        public string nom_station { get; set; }
        public int id_Vcl { get; set; }
        public string nom_Chauf { get; set; }
        public double Qté { get; set; }
        public double prix_littre { get; set; }
        public Nullable<double> prix_total { get; set; }
        public string photo { get; set; }
    
        public virtual Véhicule Véhicule { get; set; }
    }
}
