//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMATRANS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int id_Util { get; set; }
        public string nom_Util { get; set; }
        public string mot_passe { get; set; }
    }
}
