//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMATRANS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Véhicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Véhicule()
        {
            this.Bons = new HashSet<Bon>();
        }
    
        public int id_Vcl { get; set; }
        public string immatriculation { get; set; }
        public int id_marque { get; set; }
        public System.DateTime date_service { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon> Bons { get; set; }
        public virtual Marque Marque { get; set; }
    }
}
